{% set build = 0 %}
{% set strbuild = "build_" + build|string %}
{% set version = "1.0" %}

package:
  name: rsasecure_login
  version: {{ version }}

source:
  path: ../../rsasecure_login

build:
  noarch: python
  number: {{ build }}  # [linux,osx]
  string: {{ strbuild }}
  skip: true # [win]

requirements:
  host:
    - python
  run:
    - python
    - requests
    - conda

test:
  imports:
    - rsasecure_login
  commands:
    - test -f $PREFIX/bin/rsasecure_login

about:
  home: https://mooseframework.org/
  license: LGPL 2.1
  summary: 'Install Conda packages protected by an RSASecureID location'

extra:
  recipe-maintainers:
    - milljm
